#!/usr/bin/env python3
"""Check every metric's declared source against the live OpenAPI spec.

Two kinds of verification exist, and only one of them needs a token:

  STATIC   - does the endpoint exist, and does the field the ontology names
             actually appear on its 200 response? The spec answers this, now.
  LIVE     - does an AD_PARTNER token get a 200, is the data non-empty, does
             suppression fire? Only a real call answers this.

This tool does the static half and writes the live half out as a checklist,
so the day a test token lands is a sweep rather than an investigation.

    python tools/verify_sources.py            # report
    python tools/verify_sources.py --write    # also regenerate VERIFY.md
    python tools/verify_sources.py --check    # exit 1 if VERIFY.md is stale
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "reference" / "bff-openapi.json"
SCREENS = ROOT / "ontology" / "screens"
CATALOG = ROOT / "catalog"
OUT = ROOT / "VERIFY.md"

STAMP = "<!-- generated by tools/verify_sources.py - do not edit by hand -->"

# Endpoints whose scope for an AD_PARTNER token is the thing in doubt, with why.
SCOPE_DOUBT = {
    "/api/v1/dashboard/audience": (
        "clientId is documented as 'Your client UUID', but an agency owns no stores. "
        "If this is really owner-scoped, it 403s or comes back suppressed."),
    "/api/v1/clients/{brandId}/analytics": (
        "brandId is a DIFFERENT client to the caller. Whether an agency may read its own "
        "brands through this path is unverified."),
    "/api/v1/analytics/devices/{deviceId}/uptime": (
        "sits under /analytics, which elsewhere serves network-wide AdGrid-admin views."),
    "/api/v1/revenue-breakdown/{apId}": (
        "apId must equal the caller's own client. Confirm it rejects someone else's."),
    "/api/v1/client-rate-cards": (
        "returns the AP-to-Brand grid. Confirm it never leaks the AdGrid-to-AP side, "
        "which is the agency's own cost basis."),
}

# Fields the spec types loosely, so presence proves nothing about shape.
UNTYPED = {
    ("POST /api/v1/inventory/heatmap", "grid"):
        "grid is an untyped array in the spec. Whether it carries a zone or daypart axis "
        "is unknown until a real response is read.",
    ("GET /api/v1/approvals/queue", "quantityValues"):
        "quantityValues is a free-form object. What keys it holds is unknown.",
}


def load_spec():
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    return spec, spec.get("components", {}).get("schemas", {})


def resolve(schemas, name, depth=0, seen=None):
    """Flatten a schema into {property name -> dotted path}, a few levels deep."""
    seen = seen or set()
    out = {}
    if depth > 3 or name in seen or name not in schemas:
        return out
    seen = seen | {name}
    for key, val in (schemas[name].get("properties") or {}).items():
        out.setdefault(key, key)
        ref = val.get("$ref") or (val.get("items") or {}).get("$ref")
        if ref:
            child = ref.split("/")[-1]
            for k2 in resolve(schemas, child, depth + 1, seen):
                out.setdefault(k2, f"{key}.{k2}")
    return out


def op_prose(spec, method, path):
    """The endpoint's own summary and description, where the API documents itself."""
    op = (spec.get("paths", {}).get(path) or {}).get(method.lower()) or {}
    return f"{op.get('summary') or ''} {op.get('description') or ''}"


def response_fields(spec, schemas, method, path):
    """Property names on an operation's 200 response, unwrapping ApiResponseX."""
    op = (spec.get("paths", {}).get(path) or {}).get(method.lower())
    if op is None:
        return None
    content = (op.get("responses", {}).get("200", {}) or {}).get("content", {}) or {}
    ref = ""
    for body in content.values():
        ref = json.dumps(body.get("schema", {}))
        if ref:
            break
    names = re.findall(r"#/components/schemas/(\w+)", ref)
    if not names:
        return {}
    fields = {}
    for name in names:
        fields.update(resolve(schemas, name))
        data = (schemas.get(name, {}).get("properties") or {}).get("data") or {}
        inner = data.get("$ref") or (data.get("items") or {}).get("$ref")
        if inner:
            fields.update(resolve(schemas, inner.split("/")[-1]))
    return fields


def split_api(api):
    parts = api.split(" ", 1)
    if len(parts) == 2 and parts[0] in ("GET", "POST", "PUT", "DELETE"):
        return parts[0], parts[1]
    return None, None


def tokens(field_text):
    """Identifier-ish tokens from a prose field description."""
    raw = re.findall(r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*", field_text or "")
    stop = {
        "the", "and", "or", "with", "over", "on", "at", "for", "of", "a", "an", "as", "by",
        "is", "in", "to", "from", "same", "figure", "also", "divided", "unfiltered", "across",
        "roster", "computed", "not", "yet", "see", "per", "part", "outstanding", "times",
        "status", "ONLINE", "window", "day", "days", "trend", "capacity", "against", "NOT",
        "than", "it", "one", "each", "that", "which",
    }
    out = []
    for token in raw:
        tail = token.split(".")[-1]
        if tail in stop or len(tail) < 3:
            continue
        if tail.islower() and "." not in token and not re.search(r"[A-Z]", token):
            # a bare lowercase word is prose unless the schema actually has it
            out.append(tail)
            continue
        out.append(tail)
    return out


def collect_metrics():
    rows = []
    for path in sorted(SCREENS.glob("*.yaml")):
        screen = yaml.safe_load(path.read_text(encoding="utf-8"))["screen"]
        for metric in screen.get("metrics") or []:
            src = metric.get("source") or {}
            rows.append({
                "screen": screen["id"],
                "id": metric["id"],
                "label": metric.get("label", ""),
                "api": src.get("api"),
                "field": src.get("field") or "",
                "scope": src.get("scope_key"),
                "status": metric.get("status"),
            })
    return rows


def classify(rows, spec, schemas):
    cache = {}
    for row in rows:
        api = row["api"]
        if not api:
            row["verdict"] = "BLOCKED"
            row["detail"] = "no source - nothing serves this"
            continue
        if api.startswith("DERIVED"):
            row["verdict"] = "DERIVED"
            row["detail"] = "Genie's own arithmetic over other endpoints"
            continue
        method, path = split_api(api)
        if not method:
            row["verdict"] = "MALFORMED"
            row["detail"] = f"cannot parse {api!r}"
            continue
        if api not in cache:
            cache[api] = response_fields(spec, schemas, method, path)
        fields = cache[api]
        if fields is None:
            row["verdict"] = "NO SUCH ENDPOINT"
            row["detail"] = f"{method} {path} is not in the spec"
            continue
        if not row["field"].strip():
            row["verdict"] = "NO FIELD NAMED"
            row["detail"] = f"endpoint chosen, field never identified ({len(fields)} available)"
            continue
        found, missing = [], []
        for token in tokens(row["field"]):
            (found if token in fields else missing).append(token)
        if found:
            row["verdict"] = "FIELD OK"
            row["detail"] = ", ".join(sorted(set(found))[:4])
            key = (api, found[0])
            if key in UNTYPED:
                row["verdict"] = "FIELD UNTYPED"
                row["detail"] = UNTYPED[key]
        else:
            prose = op_prose(spec, method, path)
            in_prose = [t for t in missing if re.search(rf"\b{re.escape(t)}\b", prose)]
            if in_prose:
                row["verdict"] = "PROSE ONLY"
                row["detail"] = (f"{', '.join(in_prose)} appears in the endpoint's own summary but "
                                 f"not in its response schema - the row type is anonymous, so the "
                                 f"spec cannot confirm it. Read a live response.")
            else:
                row["verdict"] = "FIELD NOT FOUND"
                row["detail"] = (f"named {', '.join(missing[:3])} - none on the response. "
                                 f"Available: {', '.join(sorted(fields)[:8])}")
    return rows


ORDER = ["FIELD NOT FOUND", "NO SUCH ENDPOINT", "MALFORMED", "NO FIELD NAMED",
         "PROSE ONLY", "FIELD UNTYPED", "DERIVED", "FIELD OK", "BLOCKED"]


def report(rows):
    buckets = defaultdict(list)
    for row in rows:
        buckets[row["verdict"]].append(row)
    print(f"\nStatic check of {len(rows)} metric(s) against the live spec\n")
    for verdict in ORDER:
        if verdict in buckets:
            mark = "x" if verdict in ORDER[:4] else "-"
            print(f"  {mark} {verdict:20} {len(buckets[verdict]):3}")
    broken = sum(len(buckets[v]) for v in ORDER[:3])
    print()
    for verdict in ORDER[:5]:
        for row in buckets.get(verdict, []):
            print(f"  [{verdict}] {row['screen']}.{row['id']}")
            print(f"      {row['api']}")
            print(f"      {row['detail']}")
    return buckets, broken


def render(buckets, rows):
    def rows_for(*verdicts):
        out = []
        for verdict in verdicts:
            out.extend(buckets.get(verdict, []))
        return sorted(out, key=lambda r: (r["api"] or "", r["id"]))

    endpoints = defaultdict(list)
    for row in rows:
        if row["api"] and not row["api"].startswith("DERIVED"):
            endpoints[row["api"]].append(row)

    lines = [STAMP, "",
             "# Verification checklist",
             "",
             "Two kinds of verification exist here, and only one of them needs a token.",
             "",
             "**Static** — does the endpoint exist, and does the field the ontology names actually",
             "appear on its 200 response? The spec answers this, and this tool runs it on every commit.",
             "",
             "**Live** — does an `AD_PARTNER` token get a 200? Is the data non-empty? Does suppression",
             "fire? Only a real call answers that, and every one of those calls is listed below.",
             "",
             f"**{len(rows)} metrics.** "
             f"{len(buckets.get('FIELD OK', []))} pass the static check, "
             f"{len(rows_for('FIELD NOT FOUND', 'NO SUCH ENDPOINT', 'MALFORMED'))} fail it, "
             f"{len(buckets.get('NO FIELD NAMED', []))} name no field at all.",
             "",
             "---",
             "",
             "## Tier 0 · Fix before anyone opens a terminal",
             "",
             "These fail against the spec. No token needed to know they are wrong — the endpoint",
             "does not return what the ontology says it does.",
             ""]

    failures = rows_for("FIELD NOT FOUND", "NO SUCH ENDPOINT", "MALFORMED")
    if failures:
        lines += ["| Metric | Screen | Claimed source | Why it fails |", "|---|---|---|---|"]
        for row in failures:
            lines.append(f"| `{row['id']}` | {row['screen']} | `{row['api']}` | {row['detail']} |")
    else:
        lines.append("_None — every named field resolves against the spec._")

    lines += ["", "---", "",
              "## Tier 1 · Endpoint chosen, field never identified",
              "",
              "Not wrong, but not evidence either. Each of these picked a plausible endpoint and",
              "stopped. Until a field is named, the mapping asserts nothing a reader can check.",
              ""]
    unnamed = buckets.get("NO FIELD NAMED", [])
    if unnamed:
        grouped = defaultdict(list)
        for row in unnamed:
            grouped[row["api"]].append(row["id"])
        lines += ["| Endpoint | Metrics waiting on a field |", "|---|---|"]
        for api in sorted(grouped, key=lambda a: -len(grouped[a])):
            names = ", ".join(f"`{m}`" for m in sorted(grouped[api]))
            lines.append(f"| `{api}` | **{len(grouped[api])}** — {names} |")
    else:
        lines.append("_None._")

    lines += ["", "---", "",
              "## Tier 2 · Scope — the checks that need a real token",
              "",
              "Run these first on the day a test user exists. Each one, if it fails, invalidates",
              "every metric under it rather than just itself.",
              ""]
    for api, why in SCOPE_DOUBT.items():
        affected = [r for r in rows if r["api"] and r["api"].endswith(api)]
        if not affected:
            continue
        lines += [f"### `{api}`", "",
                  f"**{len(affected)} metric(s) ride on this.** {why}", "",
                  "- [ ] Call it with an `AD_PARTNER_ADMIN` token for the caller's own client → expect **200**",
                  "- [ ] Call it for a client the caller does not hold → expect **403**, never an empty 200",
                  "- [ ] Confirm the payload is non-empty for a client with live campaigns",
                  ""]
        lines.append("  Affected: " + ", ".join(f"`{r['id']}`" for r in sorted(affected, key=lambda r: r["id"])))
        lines.append("")

    lines += ["---", "",
              "## Tier 3 · Shape — the spec cannot settle these either way",
              "",
              "Two kinds. Either the field exists but is typed loosely, so what is inside it is",
              "unknown; or the endpoint names the field in its own summary while its row type is",
              "anonymous, so the field is almost certainly real but unconfirmable. Both need one",
              "live response, and one response clears the whole group.",
              ""]
    untyped = buckets.get("FIELD UNTYPED", []) + buckets.get("PROSE ONLY", [])
    if untyped:
        for row in sorted(untyped, key=lambda r: r["id"]):
            lines.append(f"- [ ] `{row['id']}` — {row['detail']}")
    else:
        lines.append("_None flagged._")

    lines += ["", "---", "",
              "## Tier 4 · The sweep",
              "",
              "Everything else. One call per endpoint clears every metric under it, so this is",
              f"**{len(endpoints)} calls**, not {len(rows)}.",
              "",
              "| Endpoint | Clears | Read these fields |", "|---|---|---|"]
    for api in sorted(endpoints, key=lambda a: -len(endpoints[a])):
        group = endpoints[api]
        fields = sorted({t for r in group for t in tokens(r["field"])})[:5]
        lines.append(f"| `{api}` | {len(group)} metric(s) | {', '.join(f'`{f}`' for f in fields) or '—'} |")

    lines += ["", "---", "",
              "## What 'verified' means when you tick these",
              "",
              "A metric moves from `pending_verification` to `verified` when **all four** hold:",
              "",
              "1. The call returns **200** for an `AD_PARTNER` token on its own client.",
              "2. The named field is **present and non-null** in that response.",
              "3. The value **matches what the dashboard screen shows**, to the digit.",
              "4. The same call for a client the caller does not hold returns **403** — not an empty 200.",
              "",
              "Point 4 is the one people skip. An empty 200 looks like 'no data' and reads as zero,",
              "and a zero that is really an authorization failure is the worst answer Genie can give.",
              "",
              "Suppression is separate and is not a failure: `suppressed: true` with a `reason` is a",
              "**correct** response under the k-anonymity floor of 10. Genie says suppressed, never zero.",
              ""]
    return "\n".join(lines) + "\n"


def main():
    args = set(sys.argv[1:])
    spec, schemas = load_spec()
    rows = classify(collect_metrics(), spec, schemas)
    buckets, broken = report(rows)
    text = render(buckets, rows)

    stale = False
    if "--check" in args:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        stale = current != text
        print("\nVERIFY.md is stale. Run: python tools/verify_sources.py --write"
              if stale else "\nVERIFY.md is current.")

    if "--write" in args:
        # newline="\n" explicitly — see the same note in render_kb.py.
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"\nWrote {OUT.relative_to(ROOT)}")

    # A mapping the spec contradicts is a failure in every mode, not just --check.
    # CI must not go green on an ontology that claims a field the endpoint has never returned.
    if broken:
        print(f"\n{broken} mapping(s) contradict the spec. See VERIFY.md Tier 0.")
    return 1 if (broken or stale) else 0


if __name__ == "__main__":
    sys.exit(main())
